# Generated by Django 4.0.3 on 2022-03-25 10:02

from django.db import migrations


def combine_names(apps, schema_editor):
    Student = apps.get_model('course', "Student")
    for student in Student.objects.all():
        student.name = f'{student.first_name} {student.last_name}'
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
