version: "2.2"

services:
  redis:
    image: redis
    restart: always
    env_file: ./.env
  worker:
    restart: always
    build: .
    volumes:
      - .:/online_course
    command: ["celery", "-A", "online_course", "worker"]
    env_file: ./.env
    depends_on:
      - redis
      - db
  beat:
    entrypoint: ['celery']
    command: ['-A', 'online_course', 'beat']
    env_file: ./.env
    build: .
    volumes:
      - .:/online_course
    depends_on:
      - redis
      - db
  flower:
    restart: always
    build: .
    ports:
      - "5555:5555"
    command: [ "celery", "-A", "online_course", "flower" ]
    volumes:
      - .:/online_course
    env_file: ./.env
    depends_on:
      redis:
        condition: service_started
      worker:
        condition: service_started
  web:
    restart: always
    build: .
    volumes:
      - .:/online_course
    ports:
      - "8000:8000"
    env_file: ./.env
    depends_on:
      - redis
      - db
    entrypoint: [ ]
    command: /bin/bash -c "
      ./wait_for.sh $${POSTGRES_HOST}:$${POSTGRES_PORT} &&
      python manage.py migrate &&
      python collectstatic --no-input &&
      python manage.py runserver 0.0.0.0:8000"
  db:
    restart: always
    image: postgres
    env_file: ./.env
    ports:
      - '5902:5432'
    volumes:
      - postgresqldbvolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
volumes:
  postgresqldbvolume:
    driver: local